spring:
  application:
    name: Dushnila
  main:
    web-application-type: none
    banner-mode: off
  output:
    ansi:
      enabled: detect
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: DATABASE URL
    username: DATABASE USER
    password: DATABASE PASSWORD
  profiles:
    active: @spring.profiles.active@

bot:
  name: "BOT NICKNAME"
  token: "BOT TOKEN"
  admin: "BOT ADMIN TELEGRAM USER ID"
  adminMail: "ADMIN EMAIL"

logging:
  level:
    root: INFO
  file:
    name: logs/${bot.name}_log.txt
  logback:
    rollingpolicy:
      max-file-size: 50MB
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM}.%i.log"
      max-history: 5
  pattern:
    console: "%clr([%d{yyyy-MM-dd HH:mm:ss}]){green} %clr([%-5level]){magenta} %clr([%thread]){yellow} %message%n"
    file: "%clr([%d{yyyy-MM-dd HH:mm:ss}]){green} %clr([%-5level]){magenta} %clr([%thread]){yellow} %message%n"